<?php
/**
 * Caution: This is only required for SimpleParser
 * to maintain compatibility with HHVM. Regular
 * usage on PHP will use the NativeParser.
 */

namespace SolubleTest\Japha\Bridge\Driver\Pjb62\Exception;

use Soluble\Japha\Bridge\Driver\Pjb62\Exception\JavaException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-13 at 10:21:03.
 */
class JavaExceptionTest extends \PHPUnit_Framework_TestCase
{
    public function testGetMessage()
    {
        $e = new JavaException('java.lang.Exception', 'cool');
        $this->assertEquals('cool', $e->getMessage());
        $this->assertNull($e->get__signature());
        $this->assertInternalType('int', $e->get__java());
        $this->assertInternalType('int', $e->__getJavaInternalObjectId());

        $e2 = new JavaException('java.lang.Exception', 'cool3', $e);
        $this->assertEquals('cool3', $e2->getMessage());
    }
}
