<?php

/*
 * Soluble Japha
 *
 * @link      https://github.com/belgattitude/soluble-japha
 * @copyright Copyright (c) 2013-2017 Vanvelthem Sébastien
 * @license   MIT License https://github.com/belgattitude/soluble-japha/blob/master/LICENSE.md
 */

namespace SolubleTest\Japha\Bridge\Driver\Pjb62\Exception;

use Soluble\Japha\Bridge\Driver\Pjb62\Exception\JavaException;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-13 at 10:21:03.
 */
class JavaExceptionTest extends TestCase
{
    public function testGetMessage()
    {
        $e = new JavaException('java.lang.Exception', 'cool');
        $this->assertEquals('cool', $e->getMessage());
        $this->assertNull($e->get__signature());
        $this->assertInternalType('int', $e->get__java());
        $this->assertInternalType('int', $e->__getJavaInternalObjectId());

        $e2 = new JavaException('java.lang.Exception', 'cool3', $e);
        $this->assertEquals('cool3', $e2->getMessage());
    }
}
