<?php

/*
 * Soluble Japha
 *
 * @link      https://github.com/belgattitude/soluble-japha
 * @copyright Copyright (c) 2013-2017 Vanvelthem Sébastien
 * @license   MIT License https://github.com/belgattitude/soluble-japha/blob/master/LICENSE.md
 */

namespace SolubleTest\Japha\Bridge\Driver\Pjb62\Exception;

use Soluble\Japha\Bridge\Driver\Pjb62\Exception\JavaBridgeException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-13 at 10:21:03.
 */
class JavaBridgeExceptionTest extends \PHPUnit_Framework_TestCase
{
    public function testToString()
    {
        $e = new JavaBridgeException('cool');
        $this->assertEquals('cool', (string) $e);
    }
}
