<?php
/**
 * Caution: This is only required for SimpleParser
 * to maintain compatibility with HHVM. Regular
 * usage on PHP will use the NativeParser.
 */

namespace SolubleTest\Japha\Bridge\Driver\Pjb62\Exception;

use Soluble\Japha\Bridge\Driver\Pjb62\Exception\JavaBridgeException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-13 at 10:21:03.
 */
class JavaBridgeExceptionTest extends \PHPUnit_Framework_TestCase
{
    public function testToString()
    {
        $e = new JavaBridgeException('cool');
        $this->assertEquals('cool', (string) $e);
    }
}
