imports:
    - php
filter:
    paths: [src/*]
    excluded_paths: [test/*, vendor/*, config/*, bin/*, doc/*]
tools:
    external_code_coverage: 
        timeout: 120
    php_cpd:
        excluded_dirs: [vendor, test, bin, doc, config]    
    php_pdepend:
        excluded_dirs: [vendor, test, bin, doc, config]     
    #php_code_sniffer: true
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: { }
    php_loc: 
        excluded_dirs: [vendor, test, bin, doc, config]        
    php_cs_fixer:
        config:
            level: psr2
    php_analyzer: true
    php_hhvm: false
    php_mess_detector: true
