imports:
    - php
filter:
    paths: [src/*]
    excluded_paths: [test/*, vendor/*, bin/*, doc/*]
before_commands:
    - 'composer install --dev --prefer-source' 
    - 'composer require belgattitude/pjbserver-tools'
tools:
    external_code_coverage: 
        timeout: 20
    php_cpd:
        excluded_dirs: [vendor, test, bin, doc]    
    php_pdepend:
        excluded_dirs: [vendor, test, bin, doc]     
    #php_code_sniffer: true
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: { }
    php_loc: 
        excluded_dirs: [vendor, test, bin, doc]        
    php_cs_fixer:
        config:
            level: psr2
    php_analyzer: true
    php_hhvm: false
    php_mess_detector: true
