<?php

namespace SolubleTest\Japha\Bridge\Driver\Pjb62;

use Soluble\Japha\Bridge\Adapter;
use Soluble\Japha\Bridge\Driver\Pjb62\CacheEntry;
use Soluble\Japha\Bridge\Driver\Pjb62\SimpleFactory;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-13 at 10:21:03.
 */
class CacheEntryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var string
     */
    protected $servlet_address;

    /**
     * @var string
     */
    protected $options;

    /**
     * @var Adapter
     */
    protected $adapter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        \SolubleTestFactories::startJavaBridgeServer();
        $this->servlet_address = \SolubleTestFactories::getJavaBridgeServerAddress();
        $this->adapter = new Adapter([
            'driver' => 'Pjb62',
            'servlet_address' => $this->servlet_address,
        ]);
    }

    public function testCacheEntry()
    {
        $fmt = 'fmt';
        $signature = 'signature';
        $factory = new SimpleFactory($this->adapter->getDriver()->getClient()->getClient());
        $resultVoid = true;

        $ce = new CacheEntry($fmt, $signature, $factory, $resultVoid);

        $this->assertEquals($fmt, $ce->fmt);
        $this->assertEquals($signature, $ce->signature);
        $this->assertEquals($factory, $ce->factory);
        $this->assertEquals(true, $ce->resultVoid);
    }
}
