<?php
/**
 * Caution: This is only required for SimpleParser
 * to maintain compatibility with HHVM. Regular
 * usage on PHP will use the NativeParser.
 */

namespace SolubleTest\Japha\Bridge\Driver\Pjb62;

use Soluble\Japha\Bridge\Driver\Pjb62\ParserTag;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-11-13 at 10:21:03.
 */
class ParserTagTest extends \PHPUnit_Framework_TestCase
{
    public function testParserTag()
    {
        $pt = new ParserTag();
        $this->assertEquals([], $pt->strings);
        $this->assertEquals(0, $pt->n);
    }
}
