<?php

namespace Soluble\Japha\Bridge;



/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-04 at 16:47:42.
 */
class AdapterConstructorTest extends \PHPUnit_Framework_TestCase {

    /**
     *
     * @var string
     */
    protected $servlet_address;

    /**
     *
     * @var Adapter
     */
    protected $adapter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        \SolubleTestFactories::startJavaBridgeServer();

        $this->servlet_address = \SolubleTestFactories::getJavaBridgeServerAddress();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testConstructorThrowsUnsupportedDriverException() {
        $this->setExpectedException('Soluble\Japha\Bridge\Exception\UnsupportedDriverException');
        $ba = new Adapter(array(
            'driver' => 'InvalidDriver'
        ));
    }

    public function testConstructorThrowsInvalidArgumentException() {
        $this->setExpectedException('Soluble\Japha\Bridge\Exception\InvalidArgumentException');

        $ba = new Adapter(array(
            'driver' => 'Pjb62',
            'missing_servlet_address' => ''
        ));
    }

    public function testConstructorThrowsInvalidArgumentException2() {
        $this->setExpectedException('Soluble\Japha\Bridge\Exception\InvalidArgumentException');
        $ba = new Adapter(array(
            'driver' => 'Pjb62',
            'servlet_address' => 'an invalid url'
        ));
    }

   

}
