<?php

namespace SolubleTest\Japha\Bridge;

use Soluble\Japha\Bridge\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-04 at 16:47:42.
 */
class AdapterUsageInnerClassTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var string
     */
    protected $servlet_address;

    /**
     * @var Adapter
     */
    protected $adapter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        \SolubleTestFactories::startJavaBridgeServer();

        $this->servlet_address = \SolubleTestFactories::getJavaBridgeServerAddress();

        $this->adapter = new Adapter([
            'driver' => 'Pjb62',
            'servlet_address' => $this->servlet_address,
        ]);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testInnerClass()
    {
        $ba = $this->adapter;
        $calClass = $ba->javaClass('java.util.Calendar');

        // Use inner class, notice the '$' separator
        $builder = $ba->javaClass('java.util.Calendar$Builder');

        // The inner class is successfully retrieved
        $this->assertEquals('java.util.Calendar$Builder', $ba->getClassName($builder));

        // @TODO research on this error
        //
        // PHP-JAVA-BRIDGE SERVER ERROR.
        // -----------------------------
        // But this test fails...
        // The inner class is not usable... calling a method on it
        // will throw an exception:
        // > Invoke failed: [[c:Calendar$Builder]]->setCalendarType([o:PhpParserString]).
        // > Cause: io.soluble.pjb.bridge.NoSuchProcedureException:
        // >   static setCalendarType([o:PhpParserString]). Candidates: [] VM: 1.8.0_121@http://java.oracle.com/

        /*
        $calendar = $builder->setCalendarType('japanese')
                            ->setFields($calClass->YEAR, 1, $calClass->DAY_OF_YEAR, 1)
                            ->build();
        $this->assertEquals('java.util.Calendar', $ba->getClassName($calendar);
        */
    }
}
