<?php

namespace SolubleTest\Japha\Bridge;

use Soluble\Japha\Bridge\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-04 at 16:47:42.
 */
class AdapterUsageInnerClassTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var string
     */
    protected $servlet_address;

    /**
     * @var Adapter
     */
    protected $adapter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        \SolubleTestFactories::startJavaBridgeServer();

        $this->servlet_address = \SolubleTestFactories::getJavaBridgeServerAddress();

        $this->adapter = new Adapter([
            'driver' => 'Pjb62',
            'servlet_address' => $this->servlet_address,
        ]);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testInnerClassCalendarBuilder()
    {
        $ba = $this->adapter;

        // Use inner class, notice the '$' separator
        // @see https://docs.oracle.com/javase/8/docs/api/java/util/Calendar.Builder.html
        $builder = $ba->java('java.util.Calendar$Builder');

        $this->assertEquals('java.util.Calendar$Builder', $ba->getClassName($builder));

        $calendar = $builder->setCalendarType('gregory')->build();

        $this->assertEquals('java.util.GregorianCalendar', $ba->getClassName($calendar));
    }
}
